from __future__ import annotations

import base64
import json
import mimetypes
import os
from io import BytesIO
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from flask import Flask, jsonify, redirect, render_template, request, send_from_directory, url_for
from PIL import Image, ImageOps


APP_DIR = Path(__file__).resolve().parent


def resolve_project_root() -> Path:
    """Find the Assignment 5 root directory that contains models/data/outputs."""
    candidates: list[Path] = []
    env_root = os.getenv("A5_PROJECT_ROOT")
    if env_root:
        candidates.append(Path(env_root).expanduser().resolve())

    cwd = Path.cwd().resolve()
    candidates.extend([cwd, APP_DIR, cwd.parent, APP_DIR.parent])

    for candidate in candidates:
        if (candidate / "models").exists() and (candidate / "outputs").exists():
            return candidate

    # A friendly fallback: assume app.py itself is in the assignment root.
    return APP_DIR


PROJECT_ROOT = resolve_project_root()
MODELS_DIR = PROJECT_ROOT / "models"
DATA_DIR = PROJECT_ROOT / "data"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
METRICS_DIR = OUTPUTS_DIR / "metrics"
PREDICTIONS_DIR = OUTPUTS_DIR / "predictions"
FIGURES_DIR = OUTPUTS_DIR / "figures"

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 8 * 1024 * 1024


DATASETS = {
    "fashion_mnist": {
        "name": "Fashion-MNIST",
        "type": "image",
        "description": "28 x 28 grayscale clothing classification with 10 classes.",
        "input_shape": "28 x 28 x 1",
        "classes": 10,
        "class_names": [
            "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
            "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot",
        ],
        "color_mode": "L",
    },
    "cifar100": {
        "name": "CIFAR-100",
        "type": "image",
        "description": "32 x 32 RGB image classification with 100 fine-grained classes.",
        "input_shape": "32 x 32 x 3",
        "classes": 100,
        "class_names": [
            "apple", "aquarium_fish", "baby", "bear", "beaver", "bed", "bee", "beetle", "bicycle", "bottle",
            "bowl", "boy", "bridge", "bus", "butterfly", "camel", "can", "castle", "caterpillar", "cattle",
            "chair", "chimpanzee", "clock", "cloud", "cockroach", "couch", "crab", "crocodile", "cup", "dinosaur",
            "dolphin", "elephant", "flatfish", "forest", "fox", "girl", "hamster", "house", "kangaroo", "keyboard",
            "lamp", "lawn_mower", "leopard", "lion", "lizard", "lobster", "man", "maple_tree", "motorcycle", "mountain",
            "mouse", "mushroom", "oak_tree", "orange", "orchid", "otter", "palm_tree", "pear", "pickup_truck", "pine_tree",
            "plain", "plate", "poppy", "porcupine", "possum", "rabbit", "raccoon", "ray", "road", "rocket",
            "rose", "sea", "seal", "shark", "shrew", "skunk", "skyscraper", "snail", "snake", "spider",
            "squirrel", "streetcar", "sunflower", "sweet_pepper", "table", "tank", "telephone", "television", "tiger", "tractor",
            "train", "trout", "tulip", "turtle", "wardrobe", "whale", "willow_tree", "wolf", "woman", "worm",
        ],
        "color_mode": "RGB",
    },
    "diabetes": {
        "name": "Diabetes 130-US Hospitals",
        "type": "tabular",
        "description": "Clinical encounter classification using the assignment's Conv1D adaptation.",
        "input_shape": "45 processed features x 1 channel",
        "classes": 3,
        "class_names": ["NO", ">30", "<30"],
    },
}

MODEL_LABELS = {
    "tensorflow": "TensorFlow / Keras",
    "pytorch": "PyTorch",
}

# Exact artifact names generated by the notebook.
MODEL_FILES = {
    ("fashion_mnist", "tensorflow", 3): "fashion_tensorflow_cnn3.keras",
    ("fashion_mnist", "tensorflow", 5): "fashion_tensorflow_cnn5.keras",
    ("cifar100", "tensorflow", 3): "cifar100_tensorflow_cnn3.keras",
    ("cifar100", "tensorflow", 5): "cifar100_tensorflow_cnn5.keras",
    ("diabetes", "tensorflow", 3): "diabetes_tensorflow_cnn3.keras",
    ("diabetes", "tensorflow", 5): "diabetes_tensorflow_cnn5.keras",
    ("fashion_mnist", "pytorch", 3): "fashion_pytorch_cnn3.pth",
    ("fashion_mnist", "pytorch", 5): "fashion_pytorch_cnn5.pth",
    ("cifar100", "pytorch", 3): "cifar100_pytorch_cnn3.pth",
    ("cifar100", "pytorch", 5): "cifar100_pytorch_cnn5.pth",
    ("diabetes", "pytorch", 3): "diabetes_pytorch_cnn3.pth",
    ("diabetes", "pytorch", 5): "diabetes_pytorch_cnn5.pth",
}


# Lazy caches keep the dashboard responsive when the user only wants to inspect metrics.
_MODEL_CACHE: dict[tuple[str, str, int], Any] = {}
_DIAB_PREPROCESSOR = None
_DIAB_RAW_CACHE = None


def model_path(dataset: str, framework: str, depth: int) -> Path:
    return MODELS_DIR / MODEL_FILES[(dataset, framework, int(depth))]


def artifact_status() -> list[dict[str, Any]]:
    rows = []
    for key, filename in MODEL_FILES.items():
        dataset, framework, depth = key
        p = MODELS_DIR / filename
        rows.append({
            "dataset": dataset,
            "dataset_name": DATASETS[dataset]["name"],
            "framework": framework,
            "framework_name": MODEL_LABELS[framework],
            "depth": depth,
            "filename": filename,
            "exists": p.exists(),
            "size_mb": round(p.stat().st_size / 1024**2, 2) if p.exists() else None,
        })
    extra = [
        "diabetes_preprocessor.joblib",
        "diabetes_label_names.json",
        "all_experiments_summary.csv",
        "run_config.json",
    ]
    for filename in extra:
        p = (MODELS_DIR / filename) if filename.endswith((".joblib", ".json")) and filename.startswith("diabetes") else (METRICS_DIR / filename)
        rows.append({
            "dataset": "supporting",
            "dataset_name": "Supporting artifact",
            "framework": "-",
            "framework_name": filename,
            "depth": None,
            "filename": filename,
            "exists": p.exists(),
            "size_mb": round(p.stat().st_size / 1024**2, 2) if p.exists() else None,
        })
    return rows


def load_results() -> pd.DataFrame:
    path = METRICS_DIR / "all_experiments_summary.csv"
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path)
    if "dataset" in df.columns:
        df["dataset_name"] = df["dataset"].map(lambda x: DATASETS.get(x, {}).get("name", x))
    if "framework" in df.columns:
        df["framework_name"] = df["framework"].map(MODEL_LABELS).fillna(df["framework"])
    return df


def safe_json(value: Any):
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    return value


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def load_torch_classes():
    import torch
    from torch import nn

    class ImageCNN(nn.Module):
        def __init__(self, in_channels, num_classes, depth=3):
            super().__init__()
            filters = [32, 64, 128, 128, 160] if depth == 5 else [32, 64, 128]
            pool_after = {0, 1} if depth == 3 else {0, 1, 3}
            blocks = []
            for i in range(depth):
                blocks += [
                    nn.Conv2d(in_channels if i == 0 else filters[i-1], filters[i], 3, padding=1, bias=False),
                    nn.BatchNorm2d(filters[i]),
                    nn.ReLU(inplace=True),
                ]
                if i in pool_after:
                    blocks.append(nn.MaxPool2d(2))
            self.features = nn.Sequential(*blocks)
            self.pool = nn.AdaptiveAvgPool2d(1)
            self.dropout = nn.Dropout(0.30)
            self.classifier = nn.Linear(filters[-1], num_classes)

        def forward(self, x):
            x = self.features(x)
            x = self.pool(x).flatten(1)
            return self.classifier(self.dropout(x))

    class TabularCNN(nn.Module):
        def __init__(self, num_classes, depth=3):
            super().__init__()
            filters = [32, 64, 128, 128, 160] if depth == 5 else [32, 64, 128]
            pool_after = {0, 1} if depth == 3 else {0, 1, 3}
            blocks = []
            for i in range(depth):
                blocks += [
                    nn.Conv1d(1 if i == 0 else filters[i-1], filters[i], kernel_size=3, padding=1, bias=False),
                    nn.BatchNorm1d(filters[i]),
                    nn.ReLU(inplace=True),
                ]
                if i in pool_after:
                    blocks.append(nn.MaxPool1d(2))
            self.features = nn.Sequential(*blocks)
            self.pool = nn.AdaptiveAvgPool1d(1)
            self.dropout = nn.Dropout(0.30)
            self.classifier = nn.Linear(filters[-1], num_classes)

        def forward(self, x):
            x = x.transpose(1, 2)
            x = self.features(x)
            x = self.pool(x).flatten(1)
            return self.classifier(self.dropout(x))

    return torch, ImageCNN, TabularCNN


def load_model(dataset: str, framework: str, depth: int):
    key = (dataset, framework, int(depth))
    if key in _MODEL_CACHE:
        return _MODEL_CACHE[key]

    path = model_path(*key)
    if not path.exists():
        raise FileNotFoundError(
            f"Model artifact not found: {path}. Run the notebook training cells first."
        )

    if framework == "tensorflow":
        import tensorflow as tf
        model = tf.keras.models.load_model(path, compile=False)
    else:
        torch, ImageCNN, TabularCNN = load_torch_classes()
        if dataset == "diabetes":
            model = TabularCNN(3, depth)
        else:
            in_channels = 1 if dataset == "fashion_mnist" else 3
            num_classes = DATASETS[dataset]["classes"]
            model = ImageCNN(in_channels, num_classes, depth)
        checkpoint = torch.load(path, map_location="cpu")
        state_dict = checkpoint.get("model_state_dict", checkpoint)
        model.load_state_dict(state_dict)
        model.eval()

    _MODEL_CACHE[key] = model
    return model


def preprocess_image(uploaded_file, dataset: str) -> Image.Image:
    """Normalize uploaded images to the dimensions used by the selected model."""
    original = Image.open(uploaded_file).convert("RGB")
    if dataset == "fashion_mnist":
        # Preserve a simple grayscale representation for the 28 x 28 Fashion-MNIST model.
        gray = ImageOps.grayscale(original)
        image = ImageOps.contain(gray, (28, 28))
        canvas = Image.new("L", (28, 28), 0)
        canvas.paste(image, ((28-image.width)//2, (28-image.height)//2))
        return canvas

    image = ImageOps.contain(original, (32, 32))
    canvas = Image.new("RGB", (32, 32), (0, 0, 0))
    canvas.paste(image, ((32-image.width)//2, (32-image.height)//2))
    return canvas


def image_prediction(uploaded_file, dataset: str, framework: str, depth: int):
    image = preprocess_image(uploaded_file, dataset)
    arr = np.asarray(image).astype(np.float32) / 255.0
    if dataset == "fashion_mnist":
        arr = arr[..., None]
        display_arr = np.asarray(image)
    else:
        display_arr = np.asarray(image)

    classes = DATASETS[dataset]["class_names"]

    if framework == "tensorflow":
        model = load_model(dataset, framework, depth)
        if dataset == "fashion_mnist":
            x = arr[None, ...]
        else:
            x = arr[None, ...]
        logits = model.predict(x, verbose=0)
        logits = np.asarray(logits)
        shifted = logits - logits.max(axis=1, keepdims=True)
        probs = np.exp(shifted)
        probs = probs / probs.sum(axis=1, keepdims=True)
        probs = probs[0]
    else:
        torch, _, _ = load_torch_classes()
        model = load_model(dataset, framework, depth)
        if dataset == "fashion_mnist":
            x = torch.from_numpy(arr.transpose(2, 0, 1)).unsqueeze(0).float()
        else:
            x = torch.from_numpy(arr.transpose(2, 0, 1)).unsqueeze(0).float()
        with torch.no_grad():
            logits = model(x)
            probs = torch.softmax(logits, dim=1).cpu().numpy()[0]

    order = np.argsort(probs)[::-1]
    top_k = min(5, len(classes))
    items = [
        {"class_id": int(i), "label": classes[int(i)], "probability": float(probs[int(i)])}
        for i in order[:top_k]
    ]
    return {
        "dataset": dataset,
        "dataset_name": DATASETS[dataset]["name"],
        "framework": framework,
        "framework_name": MODEL_LABELS[framework],
        "depth": int(depth),
        "predicted_class": int(order[0]),
        "predicted_label": classes[int(order[0])],
        "confidence": float(probs[int(order[0])]),
        "top_predictions": items,
        "image_data_url": image_to_data_url(display_arr),
        "input_shape": DATASETS[dataset]["input_shape"],
    }


def image_to_data_url(arr: np.ndarray) -> str:
    image = Image.fromarray(arr.astype(np.uint8))
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def load_diabetes_preprocessor():
    global _DIAB_PREPROCESSOR
    if _DIAB_PREPROCESSOR is None:
        import joblib
        path = MODELS_DIR / "diabetes_preprocessor.joblib"
        if not path.exists():
            raise FileNotFoundError(f"Missing {path}. Run the final Diabetes preprocessing cell first.")
        _DIAB_PREPROCESSOR = joblib.load(path)
    return _DIAB_PREPROCESSOR


def load_diabetes_raw():
    global _DIAB_RAW_CACHE
    if _DIAB_RAW_CACHE is None:
        path = DATA_DIR / "diabetes" / "diabetic_data.csv"
        if not path.exists():
            raise FileNotFoundError(f"Missing {path}. The dashboard uses it to provide a friendly sample record.")
        _DIAB_RAW_CACHE = pd.read_csv(path)
    return _DIAB_RAW_CACHE


def diabetes_feature_metadata() -> list[dict[str, Any]]:
    pre = load_diabetes_preprocessor()
    raw = load_diabetes_raw()
    metadata = []
    num_cols = []
    cat_cols = []
    num_imputer = None
    cat_imputer = None
    cat_encoder = None

    for name, transformer, columns in pre.transformers_:
        if name == "num":
            num_cols = list(columns)
            num_imputer = transformer.named_steps.get("imputer")
        elif name == "cat":
            cat_cols = list(columns)
            cat_imputer = transformer.named_steps.get("imputer")
            cat_encoder = transformer.named_steps.get("encoder")

    num_defaults = dict(zip(num_cols, num_imputer.statistics_ if num_imputer is not None else []))
    cat_defaults = dict(zip(cat_cols, cat_imputer.statistics_ if cat_imputer is not None else []))

    cat_options: dict[str, list[str]] = {}
    if cat_encoder is not None:
        for col, categories in zip(cat_cols, cat_encoder.categories_):
            cat_options[col] = [str(x) for x in categories.tolist()[:30]]

    for col in pre.feature_names_in_:
        series = raw[col] if col in raw.columns else None
        dtype = str(series.dtype) if series is not None else "object"
        kind = "numeric" if col in num_cols else "categorical"
        default = num_defaults.get(col, cat_defaults.get(col, ""))
        if pd.isna(default):
            default = ""
        metadata.append({
            "name": col,
            "kind": kind,
            "dtype": dtype,
            "default": safe_json(default),
            "options": cat_options.get(col, []),
        })
    return metadata


def parse_value(value: str, dtype: str):
    value = value.strip()
    if value == "":
        return np.nan
    if "int" in dtype:
        try:
            return int(float(value))
        except Exception:
            return np.nan
    if "float" in dtype or "double" in dtype:
        try:
            return float(value)
        except Exception:
            return np.nan
    return value


def diabetes_prediction(form_data: dict[str, str], framework: str, depth: int):
    pre = load_diabetes_preprocessor()
    metadata = diabetes_feature_metadata()
    row = {}
    for meta in metadata:
        row[meta["name"]] = parse_value(form_data.get(meta["name"], ""), meta["dtype"])

    df = pd.DataFrame([row], columns=[m["name"] for m in metadata])
    processed = pre.transform(df).astype(np.float32)[..., None]
    model = load_model("diabetes", framework, depth)

    if framework == "tensorflow":
        logits = model.predict(processed, verbose=0)
        logits = np.asarray(logits)
        shifted = logits - logits.max(axis=1, keepdims=True)
        probs = np.exp(shifted)
        probs = probs / probs.sum(axis=1, keepdims=True)
        probs = probs[0]
    else:
        torch, _, _ = load_torch_classes()
        with torch.no_grad():
            tensor = torch.from_numpy(processed).float()
            probs = torch.softmax(model(tensor), dim=1).cpu().numpy()[0]

    classes = DATASETS["diabetes"]["class_names"]
    order = np.argsort(probs)[::-1]
    predictions = [
        {"class_id": int(i), "label": classes[int(i)], "probability": float(probs[int(i)])}
        for i in order
    ]
    return {
        "predicted_class": int(order[0]),
        "predicted_label": classes[int(order[0])],
        "confidence": float(probs[int(order[0])]),
        "predictions": predictions,
        "processed_shape": list(processed.shape),
        "raw_feature_count": len(metadata),
        "framework": framework,
        "framework_name": MODEL_LABELS[framework],
        "depth": int(depth),
    }


def figure_manifest() -> list[str]:
    if not FIGURES_DIR.exists():
        return []
    return sorted([p.name for p in FIGURES_DIR.glob("*.png")])


def metrics_summary(df: pd.DataFrame) -> dict[str, Any]:
    if df.empty:
        return {"experiments": 0, "datasets": 0, "models": 0, "mean_accuracy": None}
    return {
        "experiments": int(len(df)),
        "datasets": int(df["dataset"].nunique()),
        "models": int(df["framework"].nunique() * df["conv_layers"].nunique() * df["dataset"].nunique()),
        "mean_accuracy": float(df["accuracy"].mean()),
    }


@app.route("/")
def index():
    df = load_results()
    return render_template(
        "index.html",
        datasets=DATASETS,
        frameworks=MODEL_LABELS,
        results=df.to_dict(orient="records"),
        summary=metrics_summary(df),
        artifacts=artifact_status(),
        figures=figure_manifest(),
        project_root=str(PROJECT_ROOT),
        run_config=load_json(METRICS_DIR / "run_config.json"),
    )


@app.post("/api/predict/image")
def api_predict_image():
    dataset = request.form.get("dataset", "fashion_mnist")
    framework = request.form.get("framework", "tensorflow")
    depth = int(request.form.get("depth", "5"))
    image_file = request.files.get("image")

    if dataset not in DATASETS or DATASETS[dataset]["type"] != "image":
        return jsonify({"error": "Invalid image dataset."}), 400
    if framework not in MODEL_LABELS or (dataset, framework, depth) not in MODEL_FILES:
        return jsonify({"error": "Invalid model selection."}), 400
    if image_file is None or not image_file.filename:
        return jsonify({"error": "Please choose an image file."}), 400

    try:
        result = image_prediction(image_file, dataset, framework, depth)
        return jsonify(result)
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.get("/api/diabetes/schema")
def api_diabetes_schema():
    try:
        return jsonify({"features": diabetes_feature_metadata()})
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.get("/api/diabetes/sample")
def api_diabetes_sample():
    try:
        raw = load_diabetes_raw().copy()
        sample = raw.iloc[0].to_dict()
        keep = set(load_diabetes_preprocessor().feature_names_in_.tolist())
        sample = {k: safe_json(v) for k, v in sample.items() if k in keep}
        return jsonify(sample)
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.post("/api/predict/diabetes")
def api_predict_diabetes():
    framework = request.form.get("framework", "tensorflow")
    depth = int(request.form.get("depth", "5"))
    try:
        result = diabetes_prediction(request.form.to_dict(), framework, depth)
        return jsonify(result)
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.get("/figures/<path:filename>")
def figures(filename):
    return send_from_directory(FIGURES_DIR, filename)


@app.get("/api/metrics")
def api_metrics():
    df = load_results()
    return jsonify({
        "results": df.to_dict(orient="records"),
        "summary": metrics_summary(df),
    })


if __name__ == "__main__":
    host = os.getenv("HOST", "127.0.0.1")
    port = int(os.getenv("PORT", "5000"))
    print("=" * 72)
    print("A5 CNN Dashboard")
    print("Project root:", PROJECT_ROOT)
    print("Models dir:", MODELS_DIR)
    print(f"Open: http://{host}:{port}")
    print("=" * 72)
    app.run(host=host, port=port, debug=True)
